### PR TITLE
fix plots tests

### PR DESCRIPTION
**Pull request by daschw**

### CODE REVIEW

**Comment by giordano** [comment]
Oh my... I was looking to the recipes, and the error was in the tests!  Thank you!

**Comment by giordano** [comment]
Latest version of RecipesBase supports Julia 1.0 only (why not 0.7? :confused:), while this package supports Julia 0.7 as well

**Comment by mkborregaard** [comment]
There is a version of RecipesBase that supports 0.7. It's simply that we've the convention of changing julia version numbers for each new release of RecipesBase, for maximum stability. It should cause zero problems, though, as `plotattributes` is also compatible with the 0.7 version.

**Comment by giordano** [comment]
> It's simply that we've the convention of changing julia version numbers for each new release of RecipesBase, for maximum stability. 

Julia 0.7 is literally equivalent to julia 1.0, besides deprecations. In this moment there are tons of packages broken on 1.0 but working on 0.7, the general recommendation is to stay on 0.7 for a while. Removing support for julia 0.7 goes against this.

> It should cause zero problems, though, as plotattributes is also compatible with the 0.7 version.

Tests are failing on julia 0.7 because of missing plot attributes field: https://travis-ci.org/JuliaPhysics/Measurements.jl/jobs/425501561

**Comment by mkborregaard** [comment]
Hm, that's not supposed to happen - the 0.7 version should definitely support plotattributes. (I'm aware of the relationship between julia 0.7 and 1.0).

**Comment by mkborregaard** [comment]
Ah, now I see, it's because you don't use the API but reach directly into the internal fields. #23 should work on both versions.

**Comment by daschw** [comment]
I recommend #23 instead.

**Pull request closed without merging**
